# Generated by Django 5.2.3 on 2026-08-03 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("livelocation", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="livelocationsession",
            name="metadata",
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
