# Generated by Django 5.2.3 on 2026-08-03 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("livelocation", "0002_livelocationsession_metadata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="livelocationsession",
            name="metadata",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
