# Generated by Django 5.2.3 on 2026-08-03 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("livelocation", "0003_alter_livelocationsession_metadata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="livelocationsession",
            name="metadata",
            field=models.CharField(blank=True, max_length=50000, null=True),
        ),
    ]
