# Generated by Django 5.2.3 on 2026-07-15 18:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ally", "0002_delete_firstresponder"),
    ]

    operations = [
        migrations.CreateModel(
            name="FirstResponder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Organization or individual name",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "firstresponder_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("firstaidandmedical", "Firstaidandmedical"),
                            ("abuseandviolence", "Abuseandviolence"),
                            ("accidentsanddisaster", "Accidentsanddisaster"),
                            ("lawenforcement", "Lawenforcement"),
                        ],
                        max_length=32,
                        null=True,
                    ),
                ),
                (
                    "organization_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("government", "Government"),
                            ("ngo", "Ngo"),
                            ("private", "Private"),
                            ("community", "Community"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, max_length=255, null=True),
                ),
                (
                    "phones",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of phone numbers as strings (e.g., ['+1234567890', '+0987654321'])",
                        null=True,
                    ),
                ),
                (
                    "availability",
                    models.CharField(
                        blank=True,
                        help_text="Availability e.g. '24/7'",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "socials",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="dict of social media links (e.g., {'facebook': 'https://facebook.com/firstresponder', 'twitter': 'https://twitter.com/firstresponder', website: 'https://firstresponder.org'})",
                        null=True,
                    ),
                ),
                (
                    "response_time",
                    models.CharField(
                        blank=True,
                        help_text="Average response time (e.g., '5 mins')",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of FirstResponderTag values",
                        null=True,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Additional metadata as JSON (e.g., {"key": "value"})',
                        null=True,
                    ),
                ),
                (
                    "service_areas",
                    models.JSONField(
                        blank=True,
                        default=None,
                        help_text="List of polygons, each a list of [lat, lng] pairs defining a service area.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "address",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ally.address",
                    ),
                ),
            ],
        ),
    ]
