# Generated by Django 5.2.3 on 2026-07-15 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("firstresponder", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="firstresponder",
            table="ally_firstresponder",
        ),
    ]
