"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from datetime import timedelta
from pathlib import Path
import os
from celery.schedules import crontab

# import environ
import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# initialize environment variables
env = environ.Env(DEBUG=(bool, False))

# Take environment variables from .env file
environ.Env.read_env(os.path.join(BASE_DIR, ".env"))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY")


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env("DEBUG", default=True)

ALLOWED_HOSTS = (
    [
        "10.24.246.102",
        "192.168.1.61",
        "10.216.153.102",
        "localhost",
        "0.0.0.0",
        "127.0.0.1",
    ]
    if DEBUG
    else env.list("ALLOWED_HOSTS", default=[])
)

# In production, this should be set to the actual domains that will be hosting the app.
CSRF_TRUSTED_ORIGINS = [] if DEBUG else env.list("CSRF_TRUSTED_ORIGINS", default=[])

# for cors
CORS_ALLOWED_ORIGINS = (
    []  # dev origins
    if DEBUG
    else env.list("CORS_ALLOWED_ORIGINS", default=["https://safetyally.app"])
)

# Application definition
INSTALLED_APPS = [
    # for celery results backend
    "django_celery_beat",
    "django_celery_results",
    #
    "corsheaders",  # for cors headers
    "jazzmin",  # for admin UI, optional
    "daphne",  # websocket stuff
    # all apps
    "ally.apps.AllyConfig",
    "firstresponder.apps.FirstresponderConfig",
    "livelocation.apps.LivelocationConfig",
    "waitlist.apps.WaitlistConfig",
    "allyalert.apps.AllyalertConfig",
    #
    "rest_framework",
    "rest_framework_gis",
    "rest_framework_simplejwt",
    # for GIS
    "django.contrib.gis",
    # default django apps
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    # for whitenoise
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",  # for cors headers
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            BASE_DIR / "templates",
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "django.template.context_processors.static",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = (
    # {
    #     # for testing
    #     "default": {
    #         "ENGINE": "django.db.backends.sqlite3",
    #         "NAME": BASE_DIR / "db.sqlite3",
    #     }
    # }
    {
        "default": {
            "ENGINE": "django.contrib.gis.db.backends.postgis",  # GeoDjango backend
            "NAME": "gis_db",
            "USER": "gis_user",
            "PASSWORD": "gis_pass",
            "HOST": "127.0.0.1",  # Connect via your local host
            "PORT": "5432",
        }
    }
    if DEBUG
    else {
        # for production
        "default": {
            # "ENGINE": "django.db.backends.postgresql",
            "ENGINE": "django.contrib.gis.db.backends.postgis",
            "NAME": env("DB_NAME"),
            "USER": env("DB_USER"),
            "PASSWORD": env("DB_PASSWORD"),
            "HOST": env("DB_HOST", default="localhost"),
            "PORT": env("DB_PORT", default="5432"),
        }
    }
)


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Set STATIC_ROOT to a directory where collected static files will be stored
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

# Add static files directories if needed
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),  # Your app's static folder
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        # Allows you to use the standard DRF UI Log In button
        "rest_framework.authentication.SessionAuthentication",
    ),
    # ... other DRF settings
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(weeks=500),
    "REFRESH_TOKEN_LIFETIME": timedelta(weeks=500),
    # ... other Simple JWT settings
}

AUTH_USER_MODEL = "ally.User"


# Google OAuth2 settings
GOOGLE_CLIENT_ID = env("GOOGLE_CLIENT_ID")

#
GEMINI_API_KEY = env("GEMINI_API_KEY", default="")

# gemini model to use, e.g. "gemini-2.5-flash-lite"
GEMINI_MODEL = env("GEMINI_MODEL", default="")

# social / contact links
X_URL = env("X_URL")
WEBSITE_URL = env("WEBSITE_URL")
WHATSAPP_URL = env("WHATSAPP_URL")
YOUTUBE_PLAYLIST = env("YOUTUBE_PLAYLIST")


# Daphne, I did for websockets, but I don't think I'll be using it for now. I'll keep it here just in case.
ASGI_APPLICATION = "config.asgi.application"

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [
                (
                    "127.0.0.1" if DEBUG else env("REDIS_HOST", default="127.0.0.1"),
                    env.int("REDIS_PORT", default=6379),
                )
            ],
        },
    },
}


# MARK: Celery configuration
# TODO: region -- -- endregion
# --- Celery Configuration ---
CELERY_BROKER_URL = f"redis://{"127.0.0.1" if DEBUG else env("REDIS_HOST", default="127.0.0.1")}:{env.int('REDIS_PORT', default=6379)}/1"

# Database result backend configuration (requires django-celery-results)
CELERY_RESULT_BACKEND = "django-db"
CELERY_RESULT_EXTENDED = (
    True  # Highly recommended: logs task arguments and execution graphs
)

# Security & Serialization
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_ACCEPT_CONTENT = ["json"]

# Reliability
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
CELERY_TIMEZONE = TIME_ZONE  # Synchronizes Celery with your Django project timezone


# CELERY BEAT  — periodic task schedule
CELERY_BEAT_SCHEDULE = {
    # Check for expired alerts every 5 minutes.
    # Keeps the public list view from showing stale alerts.
    "expire-stale-alerts": {
        "task": "allyalert.tasks.expire_stale_alerts",
        "schedule": crontab(minute="*/5"),
    },
    # Close orphaned live-location sessions once a day at 12:30 AM.
    "cleanup-orphaned-live-sessions": {
        "task": "livelocation.tasks.cleanup_orphaned_live_sessions",
        "schedule": crontab(hour=0, minute=30),
    },
    # syste level shit
    # Delete celery task result rows older than 30 days, once a day at 3 AM.
    # Prevents the TaskResult table from growing unboundedly.
    "cleanup-celery-results": {
        "task": "config.tasks.cleanup_celery_results",
        "schedule": crontab(hour=3, minute=0),
    },
}

# Force Celery to always use the database scheduler by default
CELERY_BEAT_SCHEDULER = "django_celery_beat.schedulers:DatabaseScheduler"

# Unchecked records sit in your database forever, degrading query speeds.
# This sets task historical data to auto-expire after 7 days.
# CELERY_RESULT_EXPIRES = 60 * 60 * 24 * 7

# Stop words
STOP_WORDS = set(env.list("STOP_WORDS", default=[]))


# Jazzmin settings for admin UI, optional
USE_JAZZMIN = env("USE_JAZZMIN", default=True)


JAZZMIN_SETTINGS = (
    {}
    if not USE_JAZZMIN
    else {
        "site_title": "Ally Admin",
        "site_header": "Ally",
        "site_brand": "Ally",
        "welcome_sign": "Welcome to the Ally Admin",
        "copyright": "Ally",
        # Top menu links
        "topmenu_links": [
            {"name": "Home", "url": "admin:index", "permissions": ["auth.view_user"]},
            {"name": "Site", "url": "/", "new_window": True},
        ],
        # Side menu
        "show_sidebar": True,
        "navigation_expanded": True,
        # Icons for models (uses Font Awesome 5)
        "icons": {
            "auth": "fas fa-users-cog",
            "auth.Group": "fas fa-layer-group",
            "ally.User": "fas fa-user",
            "ally.MyInformation": "fas fa-id-card",
            "firstresponder.FirstResponder": "fas fa-ambulance",
            "waitlist.WaitlistEntry": "fas fa-hourglass-half",
            "ally.Address": "fas fa-map-marker-alt",
            "livelocation.LiveLocationSession": "fas fa-broadcast-tower",
            "livelocation.SessionParticipant": "fas fa-street-view",
        },
        "default_icon_parents": "fas fa-chevron-circle-right",
        "default_icon_children": "fas fa-circle",
        # UI tweaks
        "related_modal_active": False,
    }
)

JAZZMIN_UI_TWEAKS = (
    {}
    if not USE_JAZZMIN
    else {
        "theme": "cosmo",  # bootswatch theme — try: flatly, darkly, cosmo, litera
        "default_theme_mode": "auto",
        "navbar": "navbar-dark",
        "sidebar": "sidebar-dark-primary",
    }
)

#  FOR POST GIS, GDAL --  if running on windowss
if os.name == "nt":
    # Point Django directly to the main GDAL DLL file
    GDAL_LIBRARY_PATH = r"C:\Program Files\GDAL\gdal.dll"

    # Point Django directly to the GEOS C-API DLL file
    GEOS_LIBRARY_PATH = r"C:\Program Files\GDAL\geos_c.dll"

    # Optional: Set the PROJ data directory if you hit coordinate transformation errors later
    os.environ["PROJ_LIB"] = r"C:\Program Files\GDAL\projlib"
