"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from datetime import timedelta
from pathlib import Path
import os

# import environ
import environ


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# initialize environment variables
env = environ.Env(DEBUG=(bool, False))

# Take environment variables from .env file
environ.Env.read_env(os.path.join(BASE_DIR, ".env"))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY")


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env("DEBUG", default=True)

ALLOWED_HOSTS = (
    [
        "10.24.246.102",
        "192.168.1.61",
        "10.216.153.102",
        "localhost",
        "0.0.0.0",
    ]
    if DEBUG
    else env.list("ALLOWED_HOSTS", default=[])
)

# In production, this should be set to the actual domains that will be hosting the app.
CSRF_TRUSTED_ORIGINS = [] if DEBUG else env.list("CSRF_TRUSTED_ORIGINS", default=[])

# Application definition

INSTALLED_APPS = [
    #
    "jazzmin",  # for admin UI, optional
    "daphne",
    "ally.apps.AllyConfig",
    "rest_framework",
    "rest_framework_simplejwt",
    #
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    # for whitenoise
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = (
    {
        # for testing
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }
    if DEBUG
    else {
        # for production
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": env("DB_NAME"),
            "USER": env("DB_USER"),
            "PASSWORD": env("DB_PASSWORD"),
            "HOST": env("DB_HOST", default="localhost"),
            "PORT": env("DB_PORT", default="5432"),
        }
    }
)


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Set STATIC_ROOT to a directory where collected static files will be stored
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

# Add static files directories if needed
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),  # Your app's static folder
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    # ... other DRF settings
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(weeks=500),
    "REFRESH_TOKEN_LIFETIME": timedelta(weeks=500),
    # ... other Simple JWT settings
}

AUTH_USER_MODEL = "ally.User"

GOOGLE_CLIENT_ID = env("GOOGLE_CLIENT_ID")

# gemini api key for flutter
GEMINI_API_KEY = env("GEMINI_API_KEY", default="")

# gemini model to use, e.g. "gemini-2.5-flash-lite"
GEMINI_MODEL = env("GEMINI_MODEL", default="")

# social / contact links
X_URL = env("X_URL")
WEBSITE_URL = env("WEBSITE_URL")
WHATSAPP_URL = env("WHATSAPP_URL")
YOUTUBE_PLAYLIST = env("YOUTUBE_PLAYLIST")


# Daphne, I did for websockets, but I don't think I'll be using it for now. I'll keep it here just in case.
ASGI_APPLICATION = "config.asgi.application"

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [
                (
                    env("REDIS_HOST", default="127.0.0.1"),
                    env.int("REDIS_PORT", default=6379),
                )
            ],
        },
    },
}

# Stop words
STOP_WORDS = set(env.list("STOP_WORDS", default=[]))


# Jazzmin settings for admin UI, optional
USE_JAZZMIN = env("USE_JAZZMIN", default=True)


JAZZMIN_SETTINGS = (
    {}
    if not USE_JAZZMIN
    else {
        "site_title": "Ally Admin",
        "site_header": "Ally",
        "site_brand": "Ally",
        "welcome_sign": "Welcome to the Ally Admin",
        "copyright": "Ally",
        # Top menu links
        "topmenu_links": [
            {"name": "Home", "url": "admin:index", "permissions": ["auth.view_user"]},
            {"name": "Site", "url": "/", "new_window": True},
        ],
        # Side menu
        "show_sidebar": True,
        "navigation_expanded": True,
        # Icons for models (uses Font Awesome 5)
        "icons": {
            "auth": "fas fa-users-cog",
            "auth.Group": "fas fa-layer-group",
            "ally.User": "fas fa-user",
            "ally.MyInformation": "fas fa-id-card",
            "ally.FirstResponder": "fas fa-ambulance",
            "ally.Address": "fas fa-map-marker-alt",
        },
        "default_icon_parents": "fas fa-chevron-circle-right",
        "default_icon_children": "fas fa-circle",
        # UI tweaks
        "related_modal_active": True,
    }
)

JAZZMIN_UI_TWEAKS = (
    {}
    if not USE_JAZZMIN
    else {
        "theme": "cosmo",  # bootswatch theme — try: flatly, darkly, cosmo, litera
        "default_theme_mode": "auto",
        "navbar": "navbar-dark",
        "sidebar": "sidebar-dark-primary",
    }
)
