# Generated by Django 5.2.3 on 2026-03-13 22:34

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Latitude of location', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Longitude of location', max_digits=9, null=True)),
                ('full_address', models.CharField(blank=True, help_text='Full address (e.g., Lagos, Nigeria)', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FirstResponder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, help_text='Organization or individual name', max_length=255, null=True)),
                ('firstresponder_type', models.CharField(blank=True, choices=[('firstaidandmedical', 'Firstaidandmedical'), ('abuseandviolence', 'Abuseandviolence'), ('accidentsanddisaster', 'Accidentsanddisaster'), ('lawenforcement', 'Lawenforcement')], max_length=32, null=True)),
                ('organization_type', models.CharField(blank=True, choices=[('government', 'Government'), ('ngo', 'Ngo'), ('private', 'Private'), ('community', 'Community')], max_length=20, null=True)),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
                ('phones', models.JSONField(blank=True, default=list, help_text="List of phone numbers as strings (e.g., ['+1234567890', '+0987654321'])", null=True)),
                ('availability', models.CharField(blank=True, help_text="Availability e.g. '24/7'", max_length=100, null=True)),
                ('socials', models.JSONField(blank=True, default=dict, help_text="dict of social media links (e.g., {'facebook': 'https://facebook.com/firstresponder', 'twitter': 'https://twitter.com/firstresponder', website: 'https://firstresponder.org'})", null=True)),
                ('response_time', models.CharField(blank=True, help_text="Average response time (e.g., '5 mins')", max_length=100, null=True)),
                ('tags', models.JSONField(blank=True, default=list, help_text='List of FirstResponderTag values', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata as JSON (e.g., {"key": "value"})', null=True)),
                ('address', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ally.address')),
            ],
        ),
        migrations.CreateModel(
            name='MyInformation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=50, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('allergies', models.JSONField(blank=True, default=list, help_text='List of allergies', null=True)),
                ('medications', models.JSONField(blank=True, default=list, help_text='List of medications', null=True)),
                ('medical_notes', models.TextField(blank=True, null=True)),
                ('organ_donor', models.BooleanField(default=False)),
                ('is_pregnant', models.BooleanField(default=False)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('trusted_contacts', models.JSONField(blank=True, default=list, help_text="List of trusted contacts (e.g., [{'name': 'John Doe', 'phone': '+1234567890'}])", null=True)),
                ('address', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ally.address')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('my_information', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ally.myinformation')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
