# Generated by Django 5.2.3 on 2026-07-15 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ally", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FirstResponder",
        ),
    ]
