# Generated by Django 5.2.3 on 2026-04-21 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ally', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstresponder',
            name='service_areas',
            field=models.JSONField(blank=True, default=None, help_text='List of polygons, each a list of [lat, lng] pairs defining a service area.', null=True),
        ),
    ]
