# Generated by Django 5.2.3 on 2026-07-16 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ally", "0002_delete_firstresponder"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="myinformation",
            table="ally_myinformation",
        ),
    ]
