# Generated by Django 5.2.3 on 2026-05-28 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ally", "0003_alter_address_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
