# Generated by Django 5.2.3 on 2026-07-17 12:16

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ally", "0003_alter_myinformation_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True,
                geography=True,
                help_text="user's last seen location",
                null=True,
                srid=4326,
            ),
        ),
    ]
