# Generated by Django 5.2.3 on 2026-07-17 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ally", "0004_user_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_streaming",
            field=models.BooleanField(
                default=False,
                help_text="Is the user currently streaming their location?",
            ),
        ),
    ]
