# Generated by Django 5.2.3 on 2026-05-28 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ally", "0004_alter_address_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=7,
                help_text="Latitude of location",
                max_digits=11,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=7,
                help_text="Longitude of location",
                max_digits=11,
                null=True,
            ),
        ),
    ]
