# Generated by Django 5.2.3 on 2026-07-22 06:31

import django.contrib.gis.db.models.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ServiceArea",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="e.g. Lagos Mainland Zone 1",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "polygon",
                    django.contrib.gis.db.models.fields.PolygonField(
                        help_text="Spatial boundary of this specific coverage zone.",
                        srid=4326,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
