# Generated by Django 5.2.3 on 2026-07-31 11:01

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("allyalert", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="allyalert",
            name="created_location",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, geography=True, null=True, srid=4326
            ),
        ),
        migrations.AlterField(
            model_name="allyalert",
            name="target_location",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, geography=True, null=True, srid=4326
            ),
        ),
    ]
