# Generated by Django 5.2.3 on 2026-07-31 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("allyalert", "0002_alter_allyalert_created_location_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alertreport",
            name="reason",
            field=models.CharField(
                choices=[
                    ("helpful", "Helpful"),
                    ("nothelpful", "Nothelpful"),
                    ("falseinformation", "Falseinformation"),
                    ("spam", "Spam"),
                    ("wronglocation", "Wronglocation"),
                    ("other", "Other"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="allyalert",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("expired", "Expired"),
                    ("removed", "Removed"),
                ],
                db_index=True,
                default="active",
                max_length=20,
            ),
        ),
    ]
