# Generated by Django 5.2.3 on 2026-08-09 15:03

import allyalert.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("allyalert", "0003_alter_alertreport_reason_alter_allyalert_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="allyalert",
            name="expires_at",
            field=models.DateTimeField(default=allyalert.models.get_default_expiration),
        ),
    ]
