# Generated by Django 5.2.3 on 2026-08-10 04:45

import allyalert.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("allyalert", "0004_alter_allyalert_expires_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="allyalert",
            name="expires_at",
            field=models.DateTimeField(
                blank=True,
                default=allyalert.models.get_default_expiration,
                help_text="After this datetime the alert is considered stale and should be marked EXPIRED.",
                null=True,
            ),
        ),
    ]
