# Generated by Django 5.2.3 on 2026-08-10 05:00

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("allyalert", "0005_alter_allyalert_expires_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="allyalert",
            name="created_location",
            field=django.contrib.gis.db.models.fields.PointField(
                geography=True, null=True, srid=4326
            ),
        ),
    ]
