# Generated by Django 5.2.3 on 2026-08-10 09:32

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("allyalert", "0006_alter_allyalert_created_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="allyalert",
            name="target_location_as_string",
            field=models.CharField(
                blank=True,
                help_text="Full address (e.g., Lagos, Nigeria)",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="allyalert",
            name="created_location",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, geography=True, null=True, srid=4326
            ),
        ),
        migrations.AlterField(
            model_name="allyalert",
            name="radius_km",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=2.0,
                help_text="How far from target_location (in km) the alert should reach.",
                max_digits=6,
                null=True,
            ),
        ),
    ]
