# Generated by Django 5.2.3 on 2026-08-10 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("allyalert", "0007_allyalert_target_location_as_string_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="allyalert",
            name="radius_km",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=2.0,
                help_text="How far from target_location (in km) the alert should reach.",
                max_digits=6,
            ),
        ),
    ]
